### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by shaguftarjpt673** [MarounMaroun/SO-Eclipse-Plugin#33]
Getting below error

Unable to read repository at https://raw.githubusercontent.com/MarounMaroun/SO-Eclipse-Plugin/master/so-eclipse-update-site/site.xml/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by MarounMaroun** [comment]
@shaguftarjpt673 how are you trying to install?
