### ISSUE TITLE
Eclipse plugins license

### ISSUE THREAD

**Issue by MarounMaroun** [MarounMaroun/SO-Eclipse-Plugin#4]
I'm very new to Eclipse plugins, I have no idea if there should be a license for the plugin.. and if so, how should this be done? Couldn't find any reference.

**Comment by LorenzoBettini** [comment]
You can specify license information in the feature project (using the feature.xml editor)

**Comment by MarounMaroun** [comment]
@LorenzoBettini thanks, will do that.
