### ISSUE TITLE
Rearrange project

### ISSUE THREAD

**Issue by MarounMaroun** [MarounMaroun/SO-Eclipse-Plugin#5]
Remove unnecessary files, refactor some of the code.

**Comment by LorenzoBettini** [comment]
In general, you should avoid putting .class files in the git repository :)
also binary artifacts should not be put into the git repository.

**Comment by MarounMaroun** [comment]
@LorenzoBettini Indeed, that's what happens when you `git add .` while not having a good `.gitignore`. Thanks for your comment.

**Comment by MarounMaroun** [comment]
@LorenzoBettini should `.settings`, `.project` and `.classpath` be included? I'm just not sure what files I should remove.

**Comment by LorenzoBettini** [comment]
Yes, they must be included since they don't refer to your local file system (the only exception is when you have a Maven project imported in Eclipse, but that's not your case).
