### ISSUE TITLE
Can't find the "Ask me" item on editor

### ISSUE THREAD

**Issue by tjliupeng** [MarounMaroun/SO-Eclipse-Plugin#8]
I use eclipse MARS. After I install the SO-plugin, restart eclipse, right click the editor, I can't find the "Ask me" menu item on the pop-up menu. Any suggestion?

**Comment by MarounMaroun** [comment]
@tjliupeng Did you have errors while installing the plugin? Also note that by "editor" I mean where you write the code, what's the extension of the file you're editing?

**Comment by tjliupeng** [comment]
@MarounMaroun， no error when installing. The file I edit is .java. I understands that "editor" is the place to write the code.

**Comment by MarounMaroun** [comment]
@tjliupeng I'm not sure why is that happening, I'm new to Eclipse plugins.. Note that I'm using Java 8, maybe this could be the issue, I'll try to figure out why.

**Comment by antonsarov** [comment]
@tjliupeng you can try to see if there are any messages in the error log view - could be that there is some hidden exception

**Comment by tjliupeng** [comment]
@antonsarov , where is the error log view?

**Comment by MarounMaroun** [comment]
@tjliupeng This tab is next to the console output, below the editor.

**Comment by dabelju** [comment]
I get this error:
![unbenannt](https://cloud.githubusercontent.com/assets/1306976/10602754/84496068-771a-11e5-852a-a31a55aaea36.PNG)

I need to work with Java 7. Can you help?

**Comment by MarounMaroun** [comment]
@dabelju You can work with Java 7, but you should install Java 8. Try to do so and let me know if it works.

**Comment by dabelju** [comment]
Yes, it works when I run Eclipse with Java 8.
For my projects I can still use Java 7.
Thanks!
